spring:
  application:
    name: KotlinFeatures
  datasource:
    url: jdbc:h2:file:/data/demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect

management.metrics.export.newrelic:
  account-id: MYACCOUNT
  api-key: MY_INSIGHTS_API_KEY

  # The interval at which metrics are sent to New Relic. See Duration.parse for the expected format.
  # The default is 1 minute.
  step: 1m
  enabled: false